/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import components.AddContent;
import components.ColorSamples;
import components.*;
import components.ResizeContent;
import components.StatusMenu;


import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author LENOVO
 */
public class RootFrame extends javax.swing.JFrame {

    /**
     * Creates new form TrangChu
     */
    public RootFrame() {
    	setTitle("Phầm mềm quản lý quầy thuốc tây K3TD");
        initComponents();
        pnlContent.add(new TrangChu());
        AddContent.setContent(pnlContent);
        resizeFrameToScreenScale();
        setFontAll(new Font(lblUser.getName(), Font.PLAIN, 14));
    }
 // Hàm này sẽ điều chỉnh kích thước frame sao cho phù hợp với tỷ lệ scale của màn hình
    private void resizeFrameToScreenScale() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize(); // Lấy kích thước màn hình
        setPreferredSize(screenSize);
        setSize(screenSize); 
        pnlMain.setPreferredSize(screenSize);
//        jPanelContent.setPreferredSize(screenSize);
//        jPanelFooter.setPreferredSize(new Dimension((int)screenSize.getWidth(),30));
//        jPanelHeader.setPreferredSize(new Dimension(1400,60));
//        jPanelMenu.setPreferredSize(new Dimension((int)screenSize.getWidth(),70));
//        
        System.out.println(screenSize);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        pnlHeaderTop = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblTienIch = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        pnlHeaderMenu = new javax.swing.JPanel();
        btnTrangChu = new javax.swing.JButton();
        btnBanHang = new javax.swing.JButton();
        btnQLDonHang = new javax.swing.JButton();
        btnQLHangHoa = new javax.swing.JButton();
        btnDoiTac = new javax.swing.JButton();
        btnNhanSu = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        pnlBody = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        pnlContent = new javax.swing.JPanel();
        Drop3 = new javax.swing.JPanel();
        btnHoaDon = new javax.swing.JButton();
        btnTraHang = new javax.swing.JButton();
        Drop4 = new javax.swing.JPanel();
        btnHangHoa = new javax.swing.JButton();
        btnDonThuocMau = new javax.swing.JButton();
        btnNhapHang = new javax.swing.JButton();
        btnXuatTra = new javax.swing.JButton();
        Drop5 = new javax.swing.JPanel();
        btnKhachHang = new javax.swing.JButton();
        btnNhaCungCap = new javax.swing.JButton();
        Drop6 = new javax.swing.JPanel();
        btnNhanVien = new javax.swing.JButton();
        btnCaLamViec = new javax.swing.JButton();
        Drop7 = new javax.swing.JPanel();
        btnTheoHangHoa = new javax.swing.JButton();
        btnTheoNhanVien = new javax.swing.JButton();
        btnTheoKhachHang = new javax.swing.JButton();
        pnlFooter = new javax.swing.JPanel();
        lblFooter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setAlignmentX(0.0F);
        pnlMain.setAlignmentY(0.0F);
        pnlMain.setPreferredSize(new java.awt.Dimension(1920, 1080));
        pnlMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMainMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlMainMouseEntered(evt);
            }
        });
        pnlMain.setLayout(new java.awt.BorderLayout());

        pnlHeader.setBackground(new java.awt.Color(193, 219, 208));
        pnlHeader.setAlignmentX(0.0F);
        pnlHeader.setAlignmentY(0.0F);
        pnlHeader.setPreferredSize(new java.awt.Dimension(1920, 130));

        pnlHeaderTop.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeaderTop.setPreferredSize(new java.awt.Dimension(1920, 60));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/K3TD_logo_small.png"))); // NOI18N

        lblTienIch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-setting-32.png"))); // NOI18N
        lblTienIch.setText("Tiện ích");
        lblTienIch.setAlignmentY(0.0F);
        lblTienIch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTienIchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTienIchMouseExited(evt);
            }
        });

        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-avatar-32.png"))); // NOI18N
        lblUser.setText("Username");
        lblUser.setPreferredSize(new java.awt.Dimension(100, 60));
        lblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUserMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlHeaderTopLayout = new javax.swing.GroupLayout(pnlHeaderTop);
        pnlHeaderTop.setLayout(pnlHeaderTopLayout);
        pnlHeaderTopLayout.setHorizontalGroup(
            pnlHeaderTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderTopLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTienIch, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlHeaderTopLayout.setVerticalGroup(
            pnlHeaderTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderTopLayout.createSequentialGroup()
                .addGroup(pnlHeaderTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTienIch))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogo)
                .addContainerGap())
        );

        pnlHeaderMenu.setBackground(new java.awt.Color(193, 219, 208));
        pnlHeaderMenu.setAlignmentX(0.0F);
        pnlHeaderMenu.setAlignmentY(0.0F);
        pnlHeaderMenu.setPreferredSize(new java.awt.Dimension(1920, 60));

        btnTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-overview-32.png"))); // NOI18N
        btnTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-overview-32.png"))); // NOI18N
        btnTrangChu.setBackground(ColorSamples.gb);
        btnTrangChu.setText("Trang chủ");
        btnTrangChu.setBorderPainted(false);
        btnTrangChu.setPreferredSize(new java.awt.Dimension(150, 50));
        btnTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTrangChuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTrangChuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTrangChuMouseExited(evt);
            }
        });
        btnTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChuActionPerformed(evt);
            }
        });
        pnlHeaderMenu.add(btnTrangChu);

        btnBanHang.setBackground(new java.awt.Color(193, 219, 208,0));
        btnBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-sell-32.png"))); // NOI18N
        btnBanHang.setText("Bán hàng");
        btnBanHang.setBorderPainted(false);
        btnBanHang.setPreferredSize(new java.awt.Dimension(150, 50));
        btnBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBanHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBanHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBanHangMouseExited(evt);
            }
        });
        btnBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanHangActionPerformed(evt);
            }
        });
        pnlHeaderMenu.add(btnBanHang);

        btnQLDonHang.setBackground(new java.awt.Color(193, 219, 208,0));
        btnQLDonHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-bill-32.png"))); // NOI18N
        btnQLDonHang.setText("Quản lý đơn hàng  ▾");
        btnQLDonHang.setBorderPainted(false);
        btnQLDonHang.setPreferredSize(new java.awt.Dimension(200, 50));
        btnQLDonHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQLDonHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQLDonHangMouseExited(evt);
            }
        });
        btnQLDonHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLDonHangActionPerformed(evt);
            }
        });
        pnlHeaderMenu.add(btnQLDonHang);

        btnQLHangHoa.setBackground(new java.awt.Color(193, 219, 208,0));
        btnQLHangHoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-product-32.png"))); // NOI18N
        btnQLHangHoa.setText("Quản lý hàng hóa ▾");
        btnQLHangHoa.setBorderPainted(false);
        btnQLHangHoa.setPreferredSize(new java.awt.Dimension(200, 50));
        btnQLHangHoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQLHangHoaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQLHangHoaMouseExited(evt);
            }
        });
        btnQLHangHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLHangHoaActionPerformed(evt);
            }
        });
        pnlHeaderMenu.add(btnQLHangHoa);

        btnDoiTac.setBackground(new java.awt.Color(193, 219, 208,0));
        btnDoiTac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-customers-32.png"))); // NOI18N
        btnDoiTac.setText("Đối tác ▾");
        btnDoiTac.setBorderPainted(false);
        btnDoiTac.setPreferredSize(new java.awt.Dimension(150, 50));
        btnDoiTac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDoiTacMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDoiTacMouseExited(evt);
            }
        });
        btnDoiTac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiTacActionPerformed(evt);
            }
        });
        pnlHeaderMenu.add(btnDoiTac);

        btnNhanSu.setBackground(new java.awt.Color(193, 219, 208,0));
        btnNhanSu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-member-32.png"))); // NOI18N
        btnNhanSu.setText("Nhân sự ▾");
        btnNhanSu.setBorderPainted(false);
        btnNhanSu.setPreferredSize(new java.awt.Dimension(150, 50));
        btnNhanSu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNhanSuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNhanSuMouseExited(evt);
            }
        });
        btnNhanSu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanSuActionPerformed(evt);
            }
        });
        pnlHeaderMenu.add(btnNhanSu);

        btnThongKe.setBackground(new java.awt.Color(193, 219, 208,0));
        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-graph-report-script-32.png"))); // NOI18N
        btnThongKe.setText("Thống kê ▾");
        btnThongKe.setBorderPainted(false);
        btnThongKe.setPreferredSize(new java.awt.Dimension(150, 50));
        btnThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThongKeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThongKeMouseExited(evt);
            }
        });
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });
        pnlHeaderMenu.add(btnThongKe);

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeaderTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlHeaderMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addComponent(pnlHeaderTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlHeaderMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMain.add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlBody.setBackground(new java.awt.Color(255, 255, 255));
        pnlBody.setAlignmentX(0.0F);
        pnlBody.setAlignmentY(0.0F);
        pnlBody.setPreferredSize(new java.awt.Dimension(1920, 140));
        pnlBody.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBodyMouseClicked(evt);
            }
        });
        pnlBody.setLayout(new java.awt.BorderLayout());

        jLayeredPane1.setAlignmentX(0.0F);
        jLayeredPane1.setAlignmentY(0.0F);

        pnlContent.setBackground(new java.awt.Color(255, 255, 255));
        pnlContent.setAlignmentX(0.0F);
        pnlContent.setAlignmentY(0.0F);
        pnlContent.setLayout(new java.awt.BorderLayout());

        Drop3.setBackground(new java.awt.Color(193, 219, 208));
        Drop3.setAlignmentX(0.0F);
        Drop3.setAlignmentY(0.0F);
        Drop3.setMinimumSize(new java.awt.Dimension(100, 90));
        Drop3.setPreferredSize(new java.awt.Dimension(200, 200));

        btnHoaDon.setBackground(new java.awt.Color(193, 219, 208));
        btnHoaDon.setText("Hóa đơn");
        btnHoaDon.setBorderPainted(false);
        btnHoaDon.setPreferredSize(new java.awt.Dimension(200, 40));
        btnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaDonActionPerformed(evt);
            }
        });

        btnTraHang.setBackground(new java.awt.Color(193, 219, 208));
        btnTraHang.setText("Trả hàng");
        btnTraHang.setBorderPainted(false);
        btnTraHang.setPreferredSize(new java.awt.Dimension(200, 40));
        btnTraHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Drop3Layout = new javax.swing.GroupLayout(Drop3);
        Drop3.setLayout(Drop3Layout);
        Drop3Layout.setHorizontalGroup(
            Drop3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTraHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Drop3Layout.setVerticalGroup(
            Drop3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Drop3Layout.createSequentialGroup()
                .addComponent(btnHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTraHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Drop4.setBackground(new java.awt.Color(193, 219, 208));
        Drop4.setPreferredSize(new java.awt.Dimension(200, 200));

        btnHangHoa.setBackground(new java.awt.Color(193, 219, 208));
        btnHangHoa.setText("Hàng hóa");
        btnHangHoa.setBorderPainted(false);
        btnHangHoa.setPreferredSize(new java.awt.Dimension(200, 40));
        btnHangHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHangHoaActionPerformed(evt);
            }
        });

        btnDonThuocMau.setBackground(new java.awt.Color(193, 219, 208));
        btnDonThuocMau.setText("Đơn thuốc mẫu");
        btnDonThuocMau.setBorderPainted(false);
        btnDonThuocMau.setPreferredSize(new java.awt.Dimension(200, 40));
        btnDonThuocMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonThuocMauActionPerformed(evt);
            }
        });

        btnNhapHang.setBackground(new java.awt.Color(193, 219, 208));
        btnNhapHang.setText("Nhập hàng");
        btnNhapHang.setBorderPainted(false);
        btnNhapHang.setPreferredSize(new java.awt.Dimension(200, 40));
        btnNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapHangActionPerformed(evt);
            }
        });

        btnXuatTra.setBackground(new java.awt.Color(193, 219, 208));
        btnXuatTra.setText("Xuất trả");
        btnXuatTra.setBorderPainted(false);
        btnXuatTra.setPreferredSize(new java.awt.Dimension(200, 40));
        btnXuatTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatTraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Drop4Layout = new javax.swing.GroupLayout(Drop4);
        Drop4.setLayout(Drop4Layout);
        Drop4Layout.setHorizontalGroup(
            Drop4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Drop4Layout.createSequentialGroup()
                .addGroup(Drop4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDonThuocMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXuatTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Drop4Layout.setVerticalGroup(
            Drop4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Drop4Layout.createSequentialGroup()
                .addComponent(btnHangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDonThuocMau, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXuatTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Drop5.setBackground(new java.awt.Color(193, 219, 208));
        Drop5.setPreferredSize(new java.awt.Dimension(150, 200));

        btnKhachHang.setBackground(new java.awt.Color(193, 219, 208));
        btnKhachHang.setText("Khách hàng");
        btnKhachHang.setBorderPainted(false);
        btnKhachHang.setPreferredSize(new java.awt.Dimension(150, 40));
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });

        btnNhaCungCap.setBackground(new java.awt.Color(193, 219, 208));
        btnNhaCungCap.setText("Nhà cung cấp");
        btnNhaCungCap.setBorderPainted(false);
        btnNhaCungCap.setPreferredSize(new java.awt.Dimension(150, 40));
        btnNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhaCungCapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Drop5Layout = new javax.swing.GroupLayout(Drop5);
        Drop5.setLayout(Drop5Layout);
        Drop5Layout.setHorizontalGroup(
            Drop5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Drop5Layout.createSequentialGroup()
                .addGroup(Drop5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Drop5Layout.setVerticalGroup(
            Drop5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Drop5Layout.createSequentialGroup()
                .addComponent(btnKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Drop6.setBackground(new java.awt.Color(193, 219, 208));
        Drop6.setPreferredSize(new java.awt.Dimension(150, 200));

        btnNhanVien.setBackground(new java.awt.Color(193, 219, 208));
        btnNhanVien.setText("Nhân viên");
        btnNhanVien.setBorderPainted(false);
        btnNhanVien.setPreferredSize(new java.awt.Dimension(150, 40));
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });

        btnCaLamViec.setBackground(new java.awt.Color(193, 219, 208));
        btnCaLamViec.setText("Ca làm việc");
        btnCaLamViec.setBorderPainted(false);
        btnCaLamViec.setPreferredSize(new java.awt.Dimension(150, 40));
        btnCaLamViec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaLamViecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Drop6Layout = new javax.swing.GroupLayout(Drop6);
        Drop6.setLayout(Drop6Layout);
        Drop6Layout.setHorizontalGroup(
            Drop6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Drop6Layout.createSequentialGroup()
                .addGroup(Drop6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCaLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Drop6Layout.setVerticalGroup(
            Drop6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Drop6Layout.createSequentialGroup()
                .addComponent(btnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCaLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Drop7.setBackground(new java.awt.Color(193, 219, 208));
        Drop7.setPreferredSize(new java.awt.Dimension(150, 200));

        btnTheoHangHoa.setBackground(new java.awt.Color(193, 219, 208));
        btnTheoHangHoa.setText("Theo hàng hóa");
        btnTheoHangHoa.setBorderPainted(false);
        btnTheoHangHoa.setPreferredSize(new java.awt.Dimension(150, 40));
        btnTheoHangHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTheoHangHoaActionPerformed(evt);
            }
        });

        btnTheoNhanVien.setBackground(new java.awt.Color(193, 219, 208));
        btnTheoNhanVien.setText("Theo nhân viên");
        btnTheoNhanVien.setBorderPainted(false);
        btnTheoNhanVien.setPreferredSize(new java.awt.Dimension(150, 40));
        btnTheoNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTheoNhanVienActionPerformed(evt);
            }
        });

        btnTheoKhachHang.setBackground(new java.awt.Color(193, 219, 208));
        btnTheoKhachHang.setText("Theo khách hàng");
        btnTheoKhachHang.setBorderPainted(false);
        btnTheoKhachHang.setPreferredSize(new java.awt.Dimension(150, 40));
        btnTheoKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTheoKhachHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Drop7Layout = new javax.swing.GroupLayout(Drop7);
        Drop7.setLayout(Drop7Layout);
        Drop7Layout.setHorizontalGroup(
            Drop7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Drop7Layout.createSequentialGroup()
                .addGroup(Drop7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTheoHangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTheoNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTheoKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Drop7Layout.setVerticalGroup(
            Drop7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Drop7Layout.createSequentialGroup()
                .addComponent(btnTheoHangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTheoNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTheoKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(pnlContent, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Drop3, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.setLayer(Drop4, javax.swing.JLayeredPane.POPUP_LAYER);
        jLayeredPane1.setLayer(Drop5, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane1.setLayer(Drop6, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.setLayer(Drop7, javax.swing.JLayeredPane.PALETTE_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Drop3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1714, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Drop4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1714, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(Drop5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1739, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(Drop6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1739, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(Drop7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1739, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(Drop3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(870, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(Drop4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(870, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(Drop5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(870, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(Drop6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(870, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(Drop7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(870, Short.MAX_VALUE)))
        );

        pnlBody.add(jLayeredPane1, java.awt.BorderLayout.CENTER);

        pnlMain.add(pnlBody, java.awt.BorderLayout.CENTER);

        pnlFooter.setPreferredSize(new java.awt.Dimension(1920, 30));

        lblFooter.setText("Phầm mềm quản lý hiệu thuốc tây K3TD - ver1.0.0");

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
            .addGroup(pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlFooterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblFooter)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlFooterLayout.createSequentialGroup()
                    .addGap(0, 7, Short.MAX_VALUE)
                    .addComponent(lblFooter)
                    .addGap(0, 7, Short.MAX_VALUE)))
        );

        pnlMain.add(pnlFooter, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(pnlMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void pnlMainMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
    	
    }  
    private void btnCaLamViecActionPerformed(java.awt.event.ActionEvent evt) {
    	hideAllDropMenu();
        pnlContent.removeAll();
    	
    	pnlContent.revalidate();
        pnlContent.repaint();
    }     
    
    private void btnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {
    	
    	AddContent.addContent(new TrangChu());
    }                                           

    private void btnBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanHangActionPerformed
    	AddContent.addContent(new BanHangPage());
    }//GEN-LAST:event_btnBanHangActionPerformed
   
    private void hideAllDropMenu(){
        StatusMenu.temp3 = false;
        StatusMenu.temp4 = false; 
        StatusMenu.temp5 = false; 
        StatusMenu.temp6 = false; 
        StatusMenu.temp7 = false; 
        Drop3.setSize(0, 0);
        Drop4.setSize(0, 0);
        Drop5.setSize(0, 0);
        Drop6.setSize(0, 0);
        Drop7.setSize(0, 0);
    }
    private void btnQLDonHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLDonHangActionPerformed

        if(!StatusMenu.temp3){
            hideAllDropMenu();
            Drop3.setLocation(btnQLDonHang.getLocation());
            Drop3.setSize(200, 90);
            StatusMenu.temp3=!StatusMenu.temp3;
        }else{
            hideAllDropMenu();
        }
    }//GEN-LAST:event_btnQLDonHangActionPerformed

    private void btnQLHangHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLHangHoaActionPerformed
        
        if(!StatusMenu.temp4){
            hideAllDropMenu();
            Drop4.setLocation(btnQLHangHoa.getLocation());
            Drop4.setSize(200, 180);
            StatusMenu.temp4=!StatusMenu.temp4;
        }else{
           hideAllDropMenu();
        }
    }//GEN-LAST:event_btnQLHangHoaActionPerformed

    private void btnDoiTacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiTacActionPerformed
        
        if(!StatusMenu.temp5){
            hideAllDropMenu();
            Drop5.setLocation(btnDoiTac.getLocation());
            Drop5.setSize(150, 90);
            StatusMenu.temp5=!StatusMenu.temp5;
        }else{
            hideAllDropMenu();
        }
    }//GEN-LAST:event_btnDoiTacActionPerformed

    private void btnNhanSuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanSuActionPerformed
        
        if(!StatusMenu.temp6){
            hideAllDropMenu();
            Drop6.setLocation(btnNhanSu.getLocation());
            Drop6.setSize(150, 90);
            StatusMenu.temp6=!StatusMenu.temp6;
        }else{
            hideAllDropMenu();
        }
    }//GEN-LAST:event_btnNhanSuActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        
        if(!StatusMenu.temp7){
            hideAllDropMenu();
            Drop7.setLocation(btnThongKe.getLocation());
            Drop7.setSize(150, 135);
            StatusMenu.temp7=!StatusMenu.temp7;
        }else{
            hideAllDropMenu();
        }
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoaDonActionPerformed
    	AddContent.addContent(new HoaDonPage());
    }//GEN-LAST:event_btnHoaDonActionPerformed

    private void btnTraHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraHangActionPerformed
        // TODO add your handling code here:
        hideAllDropMenu();
        pnlContent.removeAll();

    	pnlContent.revalidate();
        pnlContent.repaint();
    }//GEN-LAST:event_btnTraHangActionPerformed

    private void btnHangHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHangHoaActionPerformed
    	AddContent.addContent(new HangHoaPage());
    }//GEN-LAST:event_btnHangHoaActionPerformed

    private void btnDonThuocMauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonThuocMauActionPerformed
        AddContent.addContent(new DonThuocMauPage());
    }//GEN-LAST:event_btnDonThuocMauActionPerformed

    private void btnNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapHangActionPerformed
        // TODO add your handling code here:
    	AddContent.addContent(new NhapHangPage());
    }//GEN-LAST:event_btnNhapHangActionPerformed

    private void lblTienIchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTienIchMouseEntered
        lblTienIch.setFont(new Font(lblTienIch.getName(), Font.BOLD, lblTienIch.getFont().getSize()));
    }//GEN-LAST:event_lblTienIchMouseEntered

    private void lblTienIchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTienIchMouseExited
        lblTienIch.setFont(btnBanHang.getFont());
    }//GEN-LAST:event_lblTienIchMouseExited

    private void lblUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMouseEntered
        lblUser.setFont(new Font(lblTienIch.getName(), Font.BOLD, lblTienIch.getFont().getSize()));
    }//GEN-LAST:event_lblUserMouseEntered

    private void lblUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMouseExited
        lblUser.setFont(btnBanHang.getFont());
    }//GEN-LAST:event_lblUserMouseExited
    
    private void btnTrangChuMouseEntered(java.awt.event.MouseEvent evt){
        btnTrangChu.setBackground(ColorSamples.gbHover);
    }
    
    private void btnTrangChuMouseExited(java.awt.event.MouseEvent evt){
        btnTrangChu.setBackground(ColorSamples.gb);
    }
    
    private void btnBanHangMouseEntered(java.awt.event.MouseEvent evt){
        btnBanHang.setBackground(ColorSamples.gbHover);
    }
    
    private void btnBanHangMouseExited(java.awt.event.MouseEvent evt){
        btnBanHang.setBackground(ColorSamples.gb);
    }
    
    private void btnQLDonHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLDonHangMouseEntered
        btnQLDonHang.setBackground(ColorSamples.gbHover);
    }//GEN-LAST:event_btnQLDonHangMouseEntered

    private void btnQLDonHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLDonHangMouseExited
        btnQLDonHang.setBackground(ColorSamples.gb);
    }//GEN-LAST:event_btnQLDonHangMouseExited

    private void btnQLHangHoaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLHangHoaMouseEntered
         btnQLHangHoa.setBackground(ColorSamples.gbHover);
    }//GEN-LAST:event_btnQLHangHoaMouseEntered

    private void btnQLHangHoaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLHangHoaMouseExited
         btnQLHangHoa.setBackground(ColorSamples.gb);
    }//GEN-LAST:event_btnQLHangHoaMouseExited

    private void btnDoiTacMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoiTacMouseEntered
        btnDoiTac.setBackground(ColorSamples.gbHover);
    }//GEN-LAST:event_btnDoiTacMouseEntered

    private void btnDoiTacMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoiTacMouseExited
        btnDoiTac.setBackground(ColorSamples.gb);
    }//GEN-LAST:event_btnDoiTacMouseExited

    private void btnNhanSuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanSuMouseEntered
        btnNhanSu.setBackground(ColorSamples.gbHover);
    }//GEN-LAST:event_btnNhanSuMouseEntered

    private void btnNhanSuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanSuMouseExited
        btnNhanSu.setBackground(ColorSamples.gb);
    }//GEN-LAST:event_btnNhanSuMouseExited

    private void btnThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeMouseEntered
       btnThongKe.setBackground(ColorSamples.gbHover);
    }//GEN-LAST:event_btnThongKeMouseEntered

    private void btnThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeMouseExited
        btnThongKe.setBackground(ColorSamples.gb);
    }//GEN-LAST:event_btnThongKeMouseExited

    private void btnTrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrangChuMouseClicked
         hideAllDropMenu();
    }//GEN-LAST:event_btnTrangChuMouseClicked

    private void btnBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBanHangMouseClicked
         hideAllDropMenu();
    }//GEN-LAST:event_btnBanHangMouseClicked
    private void pnlMainMouseEntered(java.awt.event.MouseEvent evt) {
                
            }
    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
        // TODO add your handling code here:
        AddContent.addContent(new KhachHangPage());
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void btnNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhaCungCapActionPerformed
        // TODO add your handling code here:
    	AddContent.addContent(new NhaCungCapPage());
    }//GEN-LAST:event_btnNhaCungCapActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        // TODO add your handling code here:
    	AddContent.addContent(new NhanVienPage());
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnXuatTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatTraActionPerformed
        // TODO add your handling code here:
    	AddContent.addContent(new XuatTraPage());
        
        

    }//GEN-LAST:event_btnXuatTraActionPerformed

    private void lblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMouseClicked
        // TODO add your handling code here:
    	AddContent.addContent(new TaiKhoanPage());
    }//GEN-LAST:event_lblUserMouseClicked

    private void pnlBodyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBodyMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlBodyMouseClicked

    private void btnTheoHangHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTheoHangHoaActionPerformed
        // TODO add your handling code here:
        AddContent.addContent(new ThongKeHangHoaPage());
    }//GEN-LAST:event_btnTheoHangHoaActionPerformed

    private void btnTheoNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTheoNhanVienActionPerformed
        // TODO add your handling code here:
        AddContent.addContent(new ThongKeNhanVien());
    }//GEN-LAST:event_btnTheoNhanVienActionPerformed

    private void btnTheoKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTheoKhachHangActionPerformed
        // TODO add your handling code here:
        AddContent.addContent(new ThongKeKhachHang());
    }//GEN-LAST:event_btnTheoKhachHangActionPerformed
    
    private void setFontAll(Font font){
        lblTienIch.setFont(font);
        lblUser.setFont(font);
        btnCaLamViec.setFont(font);
        btnDonThuocMau.setFont(font);
        btnHangHoa.setFont(font);
        btnHoaDon.setFont(font);
        btnKhachHang.setFont(font);
        btnNhaCungCap.setFont(font);
        btnNhanVien.setFont(font);
        btnNhapHang.setFont(font);
        btnTraHang.setFont(font);
        btnXuatTra.setFont(font);
        btnTrangChu.setFont(font);
        btnBanHang.setFont(font);
        btnTheoHangHoa.setFont(font);
        btnTheoKhachHang.setFont(font);
        btnTheoNhanVien.setFont(font);
        btnQLDonHang.setFont(font);
        btnQLHangHoa.setFont(font);
        btnDoiTac.setFont(font);
        btnNhanSu.setFont(font);
        btnThongKe.setFont(font);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RootFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RootFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RootFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RootFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	RootFrame rootFrame = new RootFrame();
            	rootFrame.setExtendedState(JFrame.MAXIMIZED_BOTH); // Hiển thị cửa sổ trong chế độ toàn màn hình
                rootFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Drop3;
    private javax.swing.JPanel Drop4;
    private javax.swing.JPanel Drop5;
    private javax.swing.JPanel Drop6;
    private javax.swing.JPanel Drop7;
    private javax.swing.JButton btnBanHang;
    private javax.swing.JButton btnCaLamViec;
    private javax.swing.JButton btnDoiTac;
    private javax.swing.JButton btnDonThuocMau;
    private javax.swing.JButton btnHangHoa;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnNhaCungCap;
    private javax.swing.JButton btnNhanSu;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnNhapHang;
    private javax.swing.JButton btnQLDonHang;
    private javax.swing.JButton btnQLHangHoa;
    private javax.swing.JButton btnTheoHangHoa;
    private javax.swing.JButton btnTheoKhachHang;
    private javax.swing.JButton btnTheoNhanVien;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnTraHang;
    private javax.swing.JButton btnTrangChu;
    private javax.swing.JButton btnXuatTra;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblFooter;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTienIch;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlHeaderMenu;
    private javax.swing.JPanel pnlHeaderTop;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
